# Generated by Django 6.0.4 on 2026-04-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "equipment_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="主键ID"
                    ),
                ),
                ("owner_id", models.IntegerField(max_length=8, verbose_name="设备拥有者ID")),
                ("title", models.CharField(max_length=255, verbose_name="设备名称")),
                ("category", models.CharField(max_length=50, verbose_name="上架分类")),
                ("brand", models.CharField(max_length=50, verbose_name="设备品牌")),
                ("model", models.CharField(max_length=50, verbose_name="设备型号")),
                ("description", models.TextField(verbose_name="设备描述")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="设备日租金/价格"
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="设备押金"
                    ),
                ),
                (
                    "cover_img_url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="设备封面图片存储路径"
                    ),
                ),
                ("status", models.CharField(max_length=20, verbose_name="设备状态")),
                ("location", models.CharField(max_length=255, verbose_name="设备位置")),
                ("view_count", models.IntegerField(verbose_name="设备浏览次数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="设备创建时间"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="主键ID"
                    ),
                ),
                ("user_id", models.IntegerField(max_length=8, verbose_name="用户ID")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="订单总金额"
                    ),
                ),
                ("status", models.CharField(max_length=20, verbose_name="订单状态")),
                ("shipping_address", models.TextField(verbose_name="收货地址")),
                ("contact_phone", models.CharField(max_length=20, verbose_name="联系电话")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="订单创建时间"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "order_item_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="主键ID"
                    ),
                ),
                ("order_id", models.IntegerField(max_length=8, verbose_name="订单ID")),
                (
                    "equipment_id",
                    models.IntegerField(max_length=8, verbose_name="设备ID"),
                ),
                ("rental_days", models.IntegerField(verbose_name="租借天数")),
                (
                    "rental_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="租借价格"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="子订单金额"
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="押金金额"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="子订单创建时间"),
                ),
            ],
        ),
    ]
