# Generated by Django 6.0.4 on 2026-04-09 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_authtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="listing_type",
            field=models.CharField(
                choices=[("rent", "出租"), ("sale", "出售")],
                default="rent",
                max_length=10,
                verbose_name="出租/出售",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="buyer_handover_ok",
            field=models.BooleanField(default=False, verbose_name="买家已确认交接"),
        ),
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[("rent", "租赁"), ("sale", "出售")],
                default="rent",
                max_length=10,
                verbose_name="订单类型",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="owner_handover_ok",
            field=models.BooleanField(default=False, verbose_name="出租方/卖家已确认交接"),
        ),
        migrations.AddField(
            model_name="order",
            name="owner_id",
            field=models.IntegerField(
                default=0, max_length=8, verbose_name="卖家/出租方用户ID"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="owner_return_ok",
            field=models.BooleanField(default=False, verbose_name="出租方确认归还/订单完成"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="rental_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="日租金/单价"
            ),
        ),
        migrations.CreateModel(
            name="RentalSchedule",
            fields=[
                (
                    "schedule_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="主键ID"
                    ),
                ),
                ("rental_start_time", models.DateTimeField(verbose_name="租赁开始时间")),
                ("rental_days", models.IntegerField(verbose_name="租赁天数")),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_schedules",
                        to="users.orderitem",
                        verbose_name="订单详情",
                    ),
                ),
            ],
        ),
    ]
