# Generated by Django 6.0.4 on 2026-04-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_equipment_listing_order_rental_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="buyer_return_ok",
            field=models.BooleanField(default=False, verbose_name="承租方确认已归还设备"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="owner_id",
            field=models.IntegerField(verbose_name="设备拥有者ID"),
        ),
        migrations.AlterField(
            model_name="order",
            name="owner_id",
            field=models.IntegerField(default=0, verbose_name="卖家/出租方用户ID"),
        ),
        migrations.AlterField(
            model_name="order",
            name="owner_return_ok",
            field=models.BooleanField(default=False, verbose_name="出租方确认收到归还"),
        ),
        migrations.AlterField(
            model_name="order",
            name="user_id",
            field=models.IntegerField(verbose_name="用户ID"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="equipment_id",
            field=models.IntegerField(verbose_name="设备ID"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order_id",
            field=models.IntegerField(verbose_name="订单ID"),
        ),
    ]
