# Generated by Django 6.0.4 on 2026-04-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_favorite_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="buyer_return_ok",
        ),
        migrations.AlterField(
            model_name="equipment",
            name="owner_id",
            field=models.IntegerField(max_length=8, verbose_name="设备拥有者ID"),
        ),
        migrations.AlterField(
            model_name="order",
            name="owner_id",
            field=models.IntegerField(
                default=0, max_length=8, verbose_name="卖家/出租方用户ID"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="owner_return_ok",
            field=models.BooleanField(default=False, verbose_name="出租方确认归还/订单完成"),
        ),
        migrations.AlterField(
            model_name="order",
            name="user_id",
            field=models.IntegerField(max_length=8, verbose_name="用户ID"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="equipment_id",
            field=models.IntegerField(max_length=8, verbose_name="设备ID"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order_id",
            field=models.IntegerField(max_length=8, verbose_name="订单ID"),
        ),
    ]
