# Generated by Django 6.0.4 on 2026-04-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_favorite_restore"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoWork",
            fields=[
                (
                    "work_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="作品ID"
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="发布用户ID")),
                ("image_url", models.CharField(max_length=255, verbose_name="图片地址")),
                ("camera_name", models.CharField(max_length=100, verbose_name="相机名称")),
                ("lens_name", models.CharField(max_length=100, verbose_name="镜头名称")),
                ("iso", models.CharField(max_length=30, verbose_name="感光度")),
                ("shutter_speed", models.CharField(max_length=30, verbose_name="曝光时间")),
                ("aperture", models.CharField(max_length=30, verbose_name="光圈大小")),
                (
                    "shoot_location",
                    models.CharField(max_length=255, verbose_name="拍摄地点"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("待审核", "待审核"), ("已上架", "已上架"), ("已下架", "已下架")],
                        default="待审核",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
        ),
    ]
