# Generated by Django 6.0.4 on 2026-04-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_photo_work_square"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="buyer_return_ok",
            field=models.BooleanField(default=False, verbose_name="承租方确认归还"),
        ),
    ]
