# Generated by Django 6.0.4 on 2026-04-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_photoworkcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photowork",
            name="status",
            field=models.CharField(
                choices=[
                    ("待审核", "待审核"),
                    ("已上架", "已上架"),
                    ("已下架", "已下架"),
                    ("已驳回", "已驳回"),
                ],
                default="待审核",
                max_length=20,
                verbose_name="审核状态",
            ),
        ),
    ]
