# Generated by Django 6.0.4 on 2026-04-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_order_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="owner_id",
            field=models.IntegerField(verbose_name="设备拥有者ID"),
        ),
        migrations.AlterField(
            model_name="order",
            name="deposit_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="押金金额"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="owner_id",
            field=models.IntegerField(default=0, verbose_name="卖家/出租方用户ID"),
        ),
        migrations.AlterField(
            model_name="order",
            name="rental_days",
            field=models.IntegerField(default=1, verbose_name="租借天数"),
        ),
        migrations.AlterField(
            model_name="order",
            name="user_id",
            field=models.IntegerField(verbose_name="用户ID"),
        ),
    ]
